#!/bin/zsh
# Script for creating a new tmux env with name given in first argument

SESSION_NAME=$1
FIRST_SESSION=$2

if ! tmux has-session -t $SESSION_NAME; then
  TMUX= tmux new-session -d -s $SESSION_NAME -n shell -c $FIRST_SESSION

  tmux select-window -t$SESSION_NAME:1
  tmux send-keys -t$SESSION_NAME:1 "vim" "C-m"
  tmux split-window -h -t 1 -c $FIRST_SESSION
  tmux split-window -v -c $FIRST_SESSION
  tmux resize-pane -R 30

  tmux select-window -t$SESSION_NAME:1
fi 
tmux -2 attach -t $SESSION_NAME

