set foldmethod=marker
"" User Interface {{{
set t_Co=256
colorscheme tomorrow-night

"Set line numbers
:set number

set nowrap

set smartindent

set tabstop=2

set shiftwidth=2

set expandtab

syntax on

:set laststatus=2

set clipboard=unnamed
" }}}
