alias 'vim'='mvim -v'
alias 'v'='mvim -v'
alias 'n'='nvim'
alias 'vimrc'='v ~/dotfiles/vim/vimrc.symlink'
alias 'nvimrc'='n ~/dotfiles/nvim/nvimrc.symlink'
alias 'vundle'='v ~/dotfiles/vim/vim.symlink/vundle.vim'
