alias 'vim'='nvim'
alias 'v'='nvim'
alias 'n'='nvim'
alias 'nv'='nvim'
alias 'vimrc'='v ~/dotfiles/vim/vimrc.symlink'
alias 'nvimrc'='n ~/.config/nvim/init.vim'
alias 'vundle'='v ~/dotfiles/vim/vim.symlink/vundle.vim'
